### ISSUE TITLE
apk的下载地址失效了,求更新

### ISSUE THREAD

**Issue by blog2i2j** [bytebyte6/Tv#28]
您好, 我想下载一个tv.apk, gitee的地址无法使用, 能否更新一下链接? 谢谢.

**Comment by bytebyte6** [comment]
https://github.com/bytebyte6/Tv/tree/master/tv/labtest

blog2i2j ***@***.***> 于2022年7月31日周日 20:31写道：

**Comment by bytebyte6** [comment]
因为一些原因之前的apk不再提供，以后会提交一个空壳，请关注。
